
package myweather.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GetWeatherRequestFault", targetNamespace = "http://www.example.org/WeatherSOAP/")
public class GetWeatherRequestFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GetWeatherRequestFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetWeatherRequestFaultMessage(String message, GetWeatherRequestFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetWeatherRequestFaultMessage(String message, GetWeatherRequestFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: myweather.GetWeatherRequestFault
     */
    public GetWeatherRequestFault getFaultInfo() {
        return faultInfo;
    }

}
