
package myweather.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NewWSDLFile", targetNamespace = "http://www.example.org/NewWSDLFile/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NewWSDLFile {


    /**
     * 
     * @param cityWithSelectionName
     * @param correlationId
     * @return
     *     returns java.lang.Double
     * @throws GetWeatherError_Exception
     */
    @WebMethod(operationName = "getWeather", action = "http://www.example.org/NewWSDLFile/getWeather")
    @WebResult(name = "getWeatherResponse", targetNamespace = "http://www.example.org/NewWSDLFile", partName = "parameters")

    @RequestWrapper(localName = "getWeather", targetNamespace = "http://www.example.org/NewWSDLFile/", className = "net.atos.weatherApi.GetWeather")
    @ResponseWrapper(localName = "getWeatherResponse", targetNamespace = "http://www.example.org/NewWSDLFile/", className = "net.atos.weatherApi.GetWeatherResponse")

    public GetWeatherResponse getWeather(
        @WebParam(name = "getWeatherResponse", targetNamespace = "http://www.example.org/NewWSDLFile/getWeather", partName = "parameters")
        GetWeather parameters)
        throws GetWeatherError_Exception
    ;
}
