
package myweather.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherSOAP", targetNamespace = "http://www.example.org/WeatherSOAP/", wsdlLocation = "file:/C:/Users/a881146/OneDrive%20-%20Atos/Desktop/WeatherApp/src/main/resources/WeatherSOAP.wsdl")
public class WeatherSOAP_Service
    extends Service
{

    private final static URL WEATHERSOAP_WSDL_LOCATION;
    private final static WebServiceException WEATHERSOAP_EXCEPTION;
    private final static QName WEATHERSOAP_QNAME = new QName("http://www.example.org/WeatherSOAP/", "WeatherSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/a881146/OneDrive%20-%20Atos/Desktop/WeatherApp/src/main/resources/WeatherSOAP.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERSOAP_WSDL_LOCATION = url;
        WEATHERSOAP_EXCEPTION = e;
    }

    public WeatherSOAP_Service() {
        super(__getWsdlLocation(), WEATHERSOAP_QNAME);
    }

    public WeatherSOAP_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERSOAP_QNAME, features);
    }

    public WeatherSOAP_Service(URL wsdlLocation) {
        super(wsdlLocation, WEATHERSOAP_QNAME);
    }

    public WeatherSOAP_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERSOAP_QNAME, features);
    }

    public WeatherSOAP_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherSOAP_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherSOAP
     */
    @WebEndpoint(name = "WeatherSOAPSoap")
    public WeatherSOAP getWeatherSOAPSoap() {
        return super.getPort(new QName("http://www.example.org/WeatherSOAP/", "WeatherSOAPSoap"), WeatherSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherSOAP
     */
    @WebEndpoint(name = "WeatherSOAPSoap")
    public WeatherSOAP getWeatherSOAPSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/WeatherSOAP/", "WeatherSOAPSoap"), WeatherSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERSOAP_EXCEPTION!= null) {
            throw WEATHERSOAP_EXCEPTION;
        }
        return WEATHERSOAP_WSDL_LOCATION;
    }

}
